---
- hosts: pvenodes
  tasks:
    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: proxmoxhost
        api_user: '{{ api_user }}'
        api_token_id: '{{ api_token_id }}'
        api_token_secret: '{{ api_secret }}'
        node: pve4
